[package]
name = "vncpot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
log = "0.4"
env_logger = "0.10"
chrono = "0.4"
clap = { version = "4.5.29", features = ["derive"] }
